import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import SideBar from "./Components/sidebar";
import styles from './page.module.css'
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NET BANKING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <Navbar />
        <div className={`${styles.sidebar}`}>
          <Link href="/account">Home</Link>
          <Link href="/fundtransfer">Fund Transfer</Link>
          <Link href="/">FD/ RD</Link>
          <Link href="/">Mutual Fund</Link>
        </div>
        {children}
      </body>
    </html>
  );
}

